name: API Error Payload Report
description: Submit a sanitized App Store Connect API error payload for fixture-based regression tests.
title: "[API Error] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. This template helps us capture real-world App Store Connect API error variants and prevent regressions.

        Please include a **sanitized** error body. Do not include credentials, tokens, or private user/team information.

  - type: input
    id: asc-version
    attributes:
      label: asc version
      description: Output of `asc --version`
      placeholder: 0.26.3
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform
      description: OS and architecture where the command ran
      placeholder: macOS 15.2 (arm64)
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command run
      description: Exact CLI command that produced the error
      placeholder: asc review items-add --submission SUBMISSION_ID --item-type appStoreVersions --item-id VERSION_ID
      render: shell
    validations:
      required: true

  - type: input
    id: http-status
    attributes:
      label: HTTP status code
      description: Status returned by App Store Connect API
      placeholder: "409"
    validations:
      required: true

  - type: textarea
    id: error-body
    attributes:
      label: Sanitized API error response body (JSON)
      description: Paste the full sanitized JSON response body. Keep structure and wording intact.
      render: json
      placeholder: |
        {
          "errors": [
            {
              "status": "409",
              "code": "STATE_ERROR.ENTITY_STATE_INVALID",
              "title": "appStoreVersions with id 'version-<redacted>' is not in valid state.",
              "detail": "This resource cannot be reviewed, please check associated errors to see why.",
              "meta": {
                "associatedErrors": {
                  "/v1/ageRatingDeclarations/<redacted>": [
                    {
                      "code": "ENTITY_ERROR.ATTRIBUTE.REQUIRED",
                      "detail": "You must provide a value for the attribute 'parentalControls' with this request"
                    }
                  ]
                }
              }
            }
          ]
        }
    validations:
      required: true

  - type: textarea
    id: expected-output
    attributes:
      label: Expected CLI output
      description: What should `asc` show to be actionable?
      placeholder: Show associated errors grouped by resource path.

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Reproduction steps, frequency, or any workaround.

  - type: checkboxes
    id: sanitization-check
    attributes:
      label: Sanitization checklist
      options:
        - label: I removed/redacted secrets (keys, tokens, cookies, headers)
          required: true
        - label: I removed/redacted private identifiers (app/version/submission IDs, emails, names)
          required: true
